server:
  port: 80

mybatis:
  typeAliasesPackage: com.djp.boot.model
  mapperLocations: classpath:mapper/*.xml

spring:
#  profiles: dev
  datasource:
    url: jdbc:mysql://47.107.64.59:3306/mgs_mch_tst?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: djmsq
    password: '<#b4c(we,zhP'
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
